FROM python:3.12-slim

WORKDIR /usr/src/file-preview

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir "uvicorn[standard]"

COPY . .

ENV PYTHONPATH=/usr/src/file-preview/src

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]